### ISSUE TITLE
Years "2121" and "2222" in CSV files

### ISSUE THREAD

**Issue by yotkadata** [asjadnaqvi/COVID19-European-Regional-Tracker#1]
This is a great project, thank you very much! 

I have been exploring the CSV files and I noticed that in `04_master/csv_nuts/EUROPE_COVID19_master.csv` there are some issues with the dates. Some years are "2121" (first occurrence in line 1161) and "2222" (first occurrence in line 677) instead of "2021" and "2022". I have been able to fix that after importing the file into pandas (python), but I wanted to point out that error.

Keep up the great work!

**Comment by asjadnaqvi** [comment]
Fixed in the Sep 2022 update
